language: ruby
rvm:
  - 2.5.1
git:
  submodules:
    false
before_install:
  - echo -e "\n\nmachine github.com\n  $token\n" >~/.netrc
  - git submodule update --init --recursive
install:
  - bundle install
script:
  - bundle exec jekyll build
after_success:
  - ./push_gh-pages.sh
