language: ruby
rvm:
  - 2.5.3

language: python
python:
  - "3.6"

git:
  submodules:
    false

before_install:
  - gem install bundler

install:
  - pip install -r requirements.txt
  - bundle install
  - bundle exec rake submodules_update

script:
  - bundle exec compass compile -c assets/config.rb assets/
  - sed -i '/assets\/stylesheets\//d' .gitignore
  - bundle exec jekyll build

after_success:
  - bundle exec rake push_site
