language: 
  - ruby
  - python
rvm:
  - 2.5.3
python:
  - "3.6"
git:
  submodules:
    false
install:
  - pip install -r requirements.txt
  - bundle install
  - bundle exec rake ssh2https
  - git submodule update --init --recursive
script:
  - bundle exec jekyll build
after_success:
  - ./push_gh-pages.sh
