# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 黄昭隗的个人网站
email: admin@brave1984.com
description: >- # this means to ignore newlines until "baseurl:"
  您好！我是黄昭隗，这是我的个人网站。
  书架上的读书笔记、日志里的技术实践，献给孤独的你。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brave1984.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zhaowei1984
github_username:  brave1984

# Build settings
assets: #http://1984world.com

encoding: UTF-8
markdown: kramdown
permalink: pretty

collections:
  bookshelf:
    output: true
    permalink: /:collection/:title/
  posts:
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ""
      type: "bookshelf"
    values:
      layout: "post"

  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed


pagination:
  enabled: true
  debug: false
  collection: all
  per_page: 8
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

autopages:
  enabled: true
  tags:
    layouts:
      - archives.html
    title: 标签：:tag
    permalink: '/tags/:tag/'
    enabled: true

  categories:
    layouts:
      - archives.html
    title: 分类：:cat
    permalink: '/categories/:cat'
    enabled: true

  collections:
    enabled: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
 - "*.py"
 - Rakefile
 - requirements.txt
 - README.rst
 - assets/config.rb
 - assets/sass
 - gists/
 - bookshelf/
